Some improvements to the build & release (#5)
Ran into some rough spots on the manual release, which this cleans up.

diff --git a/script/upload b/script/upload
--- a/script/upload
+++ b/script/upload
@@ -1,21 +1,31 @@
 #!/bin/bash
 
-set -x
+set -e
 
 export PATH=/snap/bin:$PATH
 
-charm whoami
-RET=$?
-if ((RET > 0)); then
-    echo "Not logged into charm store"
+if ! charm whoami > /dev/null; then
+    echo "Not logged into charm store" 2>&1
     exit 1
 fi
 
-URL=$(charm push . cs:~"$NAMESPACE"/"$CHARM" | yq r - url)
+CHARM_DST_UNZIP="$CHARM_BUILD_DIR/$CHARM"
+
+if [ ! -e "$CHARM_DST_UNZIP" ]; then
+    echo "Built charm not found" 2>&1
+    exit 1
+fi
+
+
 IMAGE_NAME="$CHARM-image"
 IMAGE=$(yq r "charms/$CHARM/metadata.yaml" "resources.$IMAGE_NAME.upstream-source")
 docker pull "$IMAGE"
-IMAGE_REV=$(charm attach cs:~"$NAMESPACE"/"$CHARM" --channel unpublished "$IMAGE_NAME=$IMAGE" | sed -e 's/uploaded revision \([0-9]*\) of.*/\1/')
+
+URL=$(charm push "$CHARM_DST_UNZIP" "cs:~$NAMESPACE/$CHARM" | yq r - url)
+echo "Uploaded: $URL"
+
+IMAGE_REV=$(charm attach cs:~"$NAMESPACE"/"$CHARM" --channel unpublished "$IMAGE_NAME=$IMAGE" | tail -n1 | sed -e 's/uploaded revision \([0-9]*\) of.*/\1/')
+echo "Attached: $IMAGE_NAME-$IMAGE_REV"
 
 if [ "$CHANNEL" != unpublished ]; then
    charm release "$URL" --channel "$CHANNEL" --resource "$IMAGE_NAME"-"$IMAGE_REV"
